spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=
spring.datasource.username=SERVOML
spring.datasource.password=QhVjI_019F
spring.jpa.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8090